### ISSUE TITLE
Twitter tags support

### ISSUE THREAD

**Issue by antonkomarev** [dragonjet/yii2-opengraph#1]
Do you plan to add twitter additional tags support?

Like this:

```
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@site_name" />
<meta name="twitter:creator" content="@creator_name" />
<meta name="twitter:domain" content="<?= Yii::$app->urlManager->hostInfo ?>" />
```

**Comment by dragonjet** [comment]
Yes, I will try to add this today. Thanks for reminding~

**Comment by dragonjet** [comment]
Added support for twitter cards, [following the reference](https://dev.twitter.com/cards/markup). Although from your example, I didn't include `twitter:domain` since it doesn't seem to be on their documentation.

**Comment by antonkomarev** [comment]
Yes, I've took it long time ago, maybe this tag is already deprecated.
