### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by vkmel** [dragonjet/yii2-opengraph#3]
How to install this on Yii2? What to include in composer.json?

**Comment by vkmel** [comment]
Any help is appreciated. thank you.

**Comment by mtzmedia** [comment]
This worked for me:

```
"require": {
  "dragonjet/yii2-opengraph": "@dev"
},
```

**Comment by bhu1st** [comment]
This worked for me on CLI:

`composer require dragonjet/yii2-opengraph @dev`

Also Check: [composer require](https://getcomposer.org/doc/03-cli.md#require)

**Comment by craigpotter** [comment]
This should be added to the README.md
